### ISSUE TITLE
安装失败，请问可以更具体一点吗？

### ISSUE THREAD

**Issue by Lix1993** [hjlarry/zhihulive#5]
1、创建MYSQL数据库，需要数据库字符集为utf8mb4，否则emoji表情字符串导致无法插入数据

第一步看不懂。。。。

**Comment by Lix1993** [comment]
3、安装依赖，并修改config.py内的相关数据库配置


Creating a virtualenv for this project...
Pipfile: C:\Users\lix\Desktop\zhihulive-async\Pipfile
Using c:\users\lix\appdata\local\programs\python\python37\python.exe (3.7.0) to create virtualenv...
Already using interpreter c:\users\lix\appdata\local\programs\python\python37\python.exe
Using base prefix 'c:\\users\\lix\\appdata\\local\\programs\\python\\python37'
c:\users\lix\appdata\local\programs\python\python37\lib\site-packages\virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in C:\Users\lix\.virtualenvs\zhihulive-async-9ykt0XZX\Scripts\python.exe
Installing setuptools, pip, wheel...done.
Setting project for zhihulive-async-9ykt0XZX to C:\Users\lix\Desktop\zhihulive-async

Virtualenv location: C:\Users\lix\.virtualenvs\zhihulive-async-9ykt0XZX
Installing dependencies from Pipfile.lock (9b7808)...
An error occurred while installing aiomysql==0.0.17! Will try again.
An error occurred while installing mysqlclient==1.3.13! Will try again.
  ================================ 23/23 - 00:00:18
Installing initially failed dependencies...
Looking in indexes: https://pypi.python.org/simple00
Collecting aiomysql==0.0.17
  Using cached https://files.pythonhosted.org/packages/be/6a/6ab59df05a223969ceb8f457e628fd1616a57c4567b6caa061d984849d2b/aiomysql-0.0.17-py3-none-any.whl

THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    aiomysql==0.0.17 from https://files.pythonhosted.org/packages/be/6a/6ab59df05a223969ceb8f457e628fd1616a57c4567b6caa061d984849d2b/aiomysql-0.0.17-py3-none-any.whl#sha256=3b6675f43017ce3b4ec411e8430bc95de1d460ac5bbd1e6eae1391b0842bb93d (from -r C:\\Users\\lix\\AppData\\Local\\Temp\\pipenv-v_ay2n6d-requirements\\pipenv-c9jtcw0v-requirement.txt (line 1)):
        Expected sha256 85a8e00ab9a1ed53b58e90d228c5539775aabcbe338dfc32d75a97ca54aca0e9
             Got        3b6675f43017ce3b4ec411e8430bc95de1d460ac5bbd1e6eae1391b0842bb93d


     ================================ 0/2 - 00:00:00

**Comment by Lix1993** [comment]
An error occurred while installing aiomysql==0.0.17! Will try again.
An error occurred while installing mysqlclient==1.3.13! Will try again.

这两个应该没有安装成功，请问怎么修改为豆瓣源呢？

**Comment by hjlarry** [comment]
用关键词 pipenv 豆瓣源 去搜索

**Comment by Whalefall8844** [comment]
你好，遇到相同错误，pip改为豆瓣 清华源都不可了，aiomysql与 mysqlclient手动安装也不行。一直提示hash对不上。

An error occurred while installing aiomysql==0.0.17! Will try again.
An error occurred while installing mysqlclient==1.3.13! Will try again.
================================ 23/23 - 00:00:18
Installing initially failed dependencies...
Looking in indexes: https://pypi.python.org/simple00
Collecting aiomysql==0.0.17
Using cached https://files.pythonhosted.org/packages/be/6a/6ab59df05a223969ceb8f457e628fd1616a57c4567b6caa061d984849d2b/aiomysql-0.0.17-py3-none-any.whl

THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
aiomysql==0.0.17 from

**Comment by hjlarry** [comment]
试试把Pipfile.lock删掉，重新用pipenv安装一遍依赖吧，这些墙的问题，我也没什么好的办法
